TARGET_SUPPORTED_KTYPES_axxiaarm = "standard preempt-rt cgl"
KERNEL_DEVICETREE_axxiaarm = "axm5516-amarillo.dtb \
				axm5516-sim.dtb"
TARGET_SUPPORTED_KTYPES_axxiaarm64 = "standard preempt-rt cgl"
KERNEL_DEVICETREE_axxiaarm64 = "intel/axm5601-emu.dtb \
				intel/axm5602-emu.dtb \
				intel/axm5604-sim.dtb \
				intel/axm5606-emu.dtb \
				intel/axm5608-sim.dtb \
				intel/axm5616-sim.dtb \
				intel/axc6704-sim.dtb \
				intel/axc6704-emu.dtb \
				intel/axc6716-sim.dtb \
				intel/axc6712-emu.dtb"
